version: '3.8'
services:
    db:
        container_name: todo_db
        image: mariadb:10.11.2
        networks:
            bp:
        ports:
            - "3306:3306"
        volumes:
            - db:/var/lib/mysql
            - ./code/:/code
        env_file:
            -   ./code/.env
        healthcheck:
            test: "exit 0"

    nginx:
        container_name: todo_nginx
        image: nginx:latest
        networks:
            bp:
            routing_proxy:
        ports:
            - "80:80"
        volumes:
            - ./docker/site.conf:/etc/nginx/conf.d/default.conf
            - ./code/:/code
        restart: always

    php:
        container_name: todo_php
        build:
            context: ./docker/php-image
            args:
                USER_ID: ${USER_ID:-1000}
                GROUP_ID: ${GROUP_ID:-1000}
        networks:
            bp:
        ports:
            - "9000:9000"
        volumes:
            - ./code/:/code
        links:
            - db
        working_dir: /code
        user: "${UID}:${GID}"
        env_file:
            - ./code/.env
        environment:
            MARIADB_URL: db
        command: > 
            sh -c "composer install; php artisan migrate:install; php artisan migrate; php artisan db:seed; php-fpm"


volumes:
    db:

networks:
    bp:
    routing_proxy:
        name: routing_proxy